# Generated by Django 5.1.1 on 2024-10-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='price',
        ),
    ]
