# Generated by Django 5.1.1 on 2024-10-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_shoe_rename_author_post_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='price',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='shoe',
            old_name='price',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='image',
        ),
        migrations.AddField(
            model_name='shoe',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
