# Generated by Django 5.1.1 on 2024-10-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_rename_price_post_author_rename_price_shoe_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='email',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='email',
            field=models.CharField(max_length=500),
        ),
    ]
