# Generated by Django 5.1.1 on 2024-10-23 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_tag_post_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
