# Generated by Django 5.1.1 on 2024-10-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0006_delete_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cost',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
